### PR TITLE
Max avatar size increased to 2MB

### PR DESCRIPTION
**Pull request by pjsier**
In reference to #241

### CODE REVIEW

**Comment by karbassi** [comment]
@pjsier since you're fixing this issue, could you upgrade `django-avatar` in `requirements.txt` to `2.2.0`

**Comment by pjsier** [comment]
@karbassi Sure! separate PR for that or keep it in this branch?

**Comment by karbassi** [comment]
@pjsier keep it in this branch. Be sure to test to make sure nothing breaks with the upgrade :D

**Comment by pjsier** [comment]
Tested installing, viewing, and uploading an avatar and it seems good!

**Pull request merged**
