### PR TITLE
Include class_ics_url in email reminder context

### PR DESCRIPTION
**Pull request by bkellgren**
https://github.com/CoderDojoChi/coderdojochi/issues/201

### CODE REVIEW

**Comment by bkellgren** [comment]
@karbassi just a reminder, this should prob be deployed next chance you get so the "add to calendar" links (already included) in the reminder emails work properly

**Comment by karbassi** [comment]
@bkellgren Did we update the template on mandrill?

**Comment by bkellgren** [comment]
Yep they are updated

**Comment by karbassi** [comment]
@bkellgren I tested on staging and it's not working for me.

**Comment by bkellgren** [comment]
@karbassi my bad, updated directly on production mandrill.  i don't think i actually have login credentials to the staging account.  If you can share with me, I can move the latest to staging also.

**Comment by karbassi** [comment]
@bkellgren I just found the template. It's just linking to the ICS URL.

Let's attach it to the email so gmail/outlook/email programs picks it up.

**Comment by karbassi** [comment]
@bkellgren also, let's use https://developers.google.com/schemas/reference/event-reservation

**Comment by bkellgren** [comment]
@karbassi agreed, #234 addresses just that.  This ticket was for a manual download link.

**Comment by karbassi** [comment]
@bkellgren Yes! You're right. This has been merged in dev. Does this also send it out for *meetings*?

**Comment by bkellgren** [comment]
I added it for meetings also, yes


On September 28, 2015 at 2:27:28 PM, Ali Karbassi (notifications@github.com) wrote:

@bkellgren Yes! You're right. This has been merged in dev. Does this also send it out for meetings?

**Pull request merged**
