### PR TITLE
Trim whitespace on user inputs

### PR DESCRIPTION
**Pull request by bkellgren**
- [x] Create base form class that trims whitespace 
- [x] #147: existing forms to extend new base class (http://chriskief.com/2012/12/21/trim-spaces-in-django-forms/)

### CODE REVIEW

**Comment by bkellgren** [comment]
@ali somehow I must have committed the last pull request (class bg images) into my local develop branch because it ended up in this one.  i guess either cherry pick the second commit here when you merge or just merge this one after the other.

**Comment by karbassi** [comment]
Hey @bkellgren, I tried to merge and test a user register (via the email signup form) and I got an error:

**Note:** I posted a first name with spaces in it (`______Ali` where the `_` is spaces) and same with the last name. The password was something simple like `12345` since it was the staging server.

```
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/coderdojo/webapps/coderdojochi_staging/src/django-registration-master/registration/views.py", line 79, in dispatch
    return super(RegistrationView, self).dispatch(request, *args, **kwargs)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/coderdojo/webapps/coderdojochi_staging/src/django-registration-master/registration/views.py", line 35, in post
    return self.form_valid(request, form)
  File "/home/coderdojo/webapps/coderdojochi_staging/src/django-registration-master/registration/views.py", line 82, in form_valid
    new_user = self.register(request, **form.cleaned_data)
  File "/home/coderdojo/webapps/coderdojochi_staging/coderdojochi/coderdojochi/views.py", line 91, in register
    user = User.objects.create_user(username, email, password, first_name=first_name, last_name=last_name)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/contrib/auth/models.py", line 183, in create_user
    **extra_fields)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/contrib/auth/models.py", line 178, in _create_user
    user.save(using=self._db)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/coderdojo/webapps/coderdojochi_staging/lib/python2.7/Django-1.7.3-py2.7.egg/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
DataError: value too long for type character varying(30)
```

**Comment by karbassi** [comment]
Seems like it's a Django issue:

http://stackoverflow.com/questions/12842239/value-too-long-for-type-character-varying30

> That is one of the issues with using email addresses for user names in Django. Many, many emails are over 30-characters. One common way to address this issues is using a custom "Authentication Backend" for email authentication. Using your own backend you can authenticate a user based on the email field instead of the username field. You can then generate the username based on that email address or using random generated usernames.

**Comment by karbassi** [comment]
I did a quick check and it doesn't seem to be trimming the first and last names.

screen shot 2015-05-06 at 14 46 02

**Comment by bkellgren** [comment]
@ali I created a new PR #181 

- the error listed above is a separate issue allowing longer email addresses
- i added trimming for first and last name at registration

**Comment by ali** [comment]
@bkellgren I think you meant to tag @karbassi, not me (@ali)

**Pull request merged**
